plugins {
    id 'com.android.application'
}

android {
    namespace 'com.godico.devhub'
    compileSdk 33

    defaultConfig {
        applicationId "com.godico.devhub"
        minSdk 26
        targetSdk 33
        versionCode 1
        versionName "1.0"
    }

    // MANDATORI MUTLAK: Beritahu Gradle untuk mengemas .so dari jniLibs
    sourceSets {
        main {
            jniLibs.srcDirs = ['src/main/jniLibs']
        }
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}
