plugins {
    id 'com.android.application'
}

android {
    namespace 'com.godico.devhub'
    compileSdk 33

    defaultConfig {
        applicationId "com.godico.devhub"
        minSdk 26
        targetSdk 33
        versionCode 1
        versionName "1.0"
    }

    sourceSets {
        main {
            jniLibs.srcDirs = ['src/main/jniLibs']
        }
    }
    
    // Nambahin ini buat fix konflik metadata
    packagingOptions {
        pickFirst 'META-INF/androidx.*'
    }
}
