name: GODICO Automated Android Build Engine

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  assemble-apk:
    runs-on: ubuntu-latest

    steps:
    - name: 1. Ambil Kode dari Repositori (Termasuk biner .so lokal)
      uses: actions/checkout@v4

    - name: 2. Siapkan Java JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: 3. Rakit APK Final via Gradle (Biner Rust sudah di dalam jniLibs)
      run: |
        chmod +x gradlew
        ./gradlew assembleDebug --rerun-tasks

    - name: 4. Amankan File APK ke GitHub Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: GODICO-DevHub-APK
        path: app/build/outputs/apk/debug/app-debug.apk
